[package]
name = "rinha-core"
version = "0.1.0"
edition = "2021"

[lib]
name = "rinha_core"
crate-type = ["staticlib"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
